sudo: false
language: python
cache: pip
python: 3.6

addons:
  apt:
    sources:
      - ppa:jonathonf/backports
    packages:
      - jpegoptim
      - optipng
      - tidy

before_install:
  - jpegoptim --version
  - optipng --version
  - tidy --version

install:
  - pip install -r requirements.txt

script:
  - ./scripts/build_app_yaml.py > app.yaml
  - nikola build
