sudo: false
language: python
cache:
  - apt
  - pip
python: 3.6

before_install:
  - sudo add-apt-repository ppa:jonathonf/backports -y
  - sudo apt-get update -q
  - >
      sudo apt-get install
        jpegoptim
        optipng
        tidy-html5

install:
  - pip install -r requirements.txt

before_script:
  - jpegoptim --version
  - optipng --version
  - tidy --version

script:
  - ./scripts/build_app_yaml.py > app.yaml
  - nikola build
